# Generated by Django 5.1.1 on 2024-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='checkout_session_id',
        ),
    ]
