# Generated by Django 5.1.1 on 2024-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Cancel', 'Cancel')], max_length=10),
        ),
    ]
