# Generated by Django 5.1.1 on 2024-10-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='car',
            new_name='rentalcars',
        ),
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
    ]
