# Generated by Django 5.1.1 on 2024-10-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrental', '0002_rename_car_rental_rentalcars_remove_car_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rentalcars',
        ),
    ]
