# Generated by Django 5.1.1 on 2024-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrental', '0003_remove_rental_rentalcars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
