# Generated by Django 5.1.1 on 2024-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrental', '0004_alter_car_price_per_day_alter_rental_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycar',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
